object Version {
  val Q             = "0.0.1-SNAPSHOT"
  val SCALA         = "2.11.7"
  val AKKA          = "2.3.9"
  val LOGBACK       = "1.1.2"
  val SCALAZ        = "7.1.3"
  val SPRAY         = "1.3.3"
  val SLICK         = "3.0.2"
  val CONFIG        = "1.3.0"
  val SCALAGUICE    = "4.0.0"
  val MYSQLCONN     = "5.1.36"
  val SCALALOGGING  = "2.1.2"
  val CUCUMBER      = "1.2.2"
  val GHERKIN       = "2.12.2"
  val DBUNIT        = "2.5.1"
  val INJECT        = "1"
  val HIKARICP      = "2.4.1"
}